name: Run Dockerfile.test

on:
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: docker:19.03.1-dind
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Build docker image
        run: cat Dockerfile.test | docker build  --tag test-image -f - .
      - name: Run docker image
        run: docker run --rm --name test-container test-image