FROM ${REGISTRY}/it/node:16-alpine
RUN apk update && apk add --no-cache make bash
WORKDIR /app
COPY package.json package.json
COPY package-lock.json package-lock.json

COPY tsconfig.json tsconfig.json
COPY tsconfig.build.json tsconfig.build.json
COPY .eslintrc.js .eslintrc.js
COPY .eslintignore .eslintignore
COPY src src
COPY versions.json versions.json
COPY example.env .env
RUN npm ci -q
CMD npm run test-ci
