export const NODE_CONFIG = 'NODE_CONFIG'
export const TRANSACTION_BROADCASTER = 'TRANSACTION_BROADCASTER'
export const SEED_MANAGER = 'SEED_MANAGER'
export const WALLETS_PROVIDER = 'GATEWAY_WALLETS_PROVIDER'
export const WAVES_TIMEOUT = 600000
export const WE_TIMEOUT = 600000