export type WaitForWavesTxMiningResponse ={
  type: number,
  id: string,
  fee: string,
  feeAssetId: null,
  timestamp: number,
  version: number,
  chainId: number,
  sender: string,
  senderPublicKey: string,
  proofs: string[],
  recipient: string,
  assetId?: string,
  feeAsset?: string,
  amount: number,
  attachment?: string,
  height: number,
  applicationStatus: string,
  spentComplexity: number,
}
